services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    #ports:
    #  - 3006:3306
    #   - 33060:33060
    volumes:
      - "./api/go_pa.sql:/docker-entrypoint-initdb.d/1.sql"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
